{% set name = "types-bleach" %}
{% set version = "6.0.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-bleach-{{ version }}.tar.gz
  sha256: 0bf3e58b2930a19a64ebac173f53d2fc897ce92b0f39048dc9fcb1eb847241b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/bleach-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for bleach
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
