{% set version = "6.2.0.20250809" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: types-bleach
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-bleach/types_bleach-{{ version }}.tar.gz
    sha256: 188d7a1119f6c953140b513ed57ba4213755695815472c19d0c22ac09c79b90b
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-html5lib

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/bleach-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for bleach
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
